### ISSUE TITLE
Problems when run example QM9

### ISSUE THREAD

**Issue by limin2021** [torchmd/torchmd-net#111]
Command:
`CUDA_VISIBLE_DEVICES=0 python scripts/train.py --conf examples/ET-QM9.yaml --dataset QM9 --log-dir output/`
 
Output:
`  File "/benchmark/science-computing/torchmd-net/torchmdnet/utils.py", line 153, in __call__
    raise ValueError(f"Unknown argument in config file: {key}")
ValueError: Unknown argument in config file: distributed_backend`

Any problems for the example?

**Comment by limin2021** [comment]
This problem can be solved by removing "distributed_backend" in file "examples/ET-QM9.yaml".

**Comment by raimis** [comment]
@limin2021 could you make a PR removing that line from the example?

**Comment by limin2021** [comment]
Sorry, I can't follow you. Can you make it clear?

**Comment by giadefa** [comment]
Done.
