### ISSUE TITLE
An error occurred in setting up the environment

### ISSUE THREAD

**Issue by mukui123** [torchmd/torchmd-net#145]
I set up the environment according to the installation manual. Every time I create a virtual environment, cudatoolkit11.7.0 will be downloaded automatically. However, my Linux cuda version is 11.6, running torchmd-train will report such an error, can you solve it? Thank you very much!
![image](https://user-images.githubusercontent.com/90401610/199138955-10601894-6a01-4726-8064-a5d70148822a.png)
![image](https://user-images.githubusercontent.com/90401610/199139051-72676bc8-ab33-4373-b456-0e6b95bc9246.png)

**Comment by giadefa** [comment]
Does your Nvidia driver support Cuda11.7? Is it new enough? try to update
the driver

**Comment by stefdoerr** [comment]
@giadefa I'm not sure that's a good idea. the rest of the packages it's pulled are for cuda 11.2 if you look at pytorch for example. It's probably better to force the installation of cudatoolkit 11.2 in this environment.
@mukui123 can you try `conda install cudatoolkit=11.2 -c conda-forge`?

**Comment by peastman** [comment]
Conda is supposed to check your driver and automatically pick the most recent toolkit compatible with it.  In practice, that doesn't work very well.  It often ends up picking a toolkit that's newer than your driver supports.  In that case, you need to force it to downgrade as @stefdoerr suggested.  We should add this to the documentation.

**Comment by mukui123** [comment]
I have reinstalled the new version of cuda, but I still get an error when running torchmd-train, could you please help me check it? Thank you very much!

Traceback (most recent call last):
  File "/home/wangchenyang/anaconda3/envs/torchmd-net/bin/torchmd-train", line 33, in <module>
    sys.exit(load_entry_point('torchmd-net', 'console_scripts', 'torchmd-train')())
  File "/home/wangchenyang/torchmd-net/torchmdnet/scripts/train.py", line 113, in main
    args = get_args()
  File "/home/wangchenyang/torchmd-net/torchmdnet/scripts/train.py", line 65, in get_args
    parser.add_argument('--prior-model', type=str, default=None, choices=priors.__all__, help='Which prior model to use')
AttributeError: module 'torchmdnet.priors' has no attribute '__all__'
