### ISSUE TITLE
CUDA version conflicts

### ISSUE THREAD

**Issue by mukui123** [torchmd/torchmd-net#147]
I followed the steps to create and activate the virtual environment according to environment.yml, but the cuda version always conflicts: First, the nnpops package in the yml file relies on cudatoolkit 11.2.2, but the official gpu only has 10.2, 11.3, and 11.6 versions
Secondly, pytorch only supports 1.11.0 and 1.12.0. CUDA only supports cpu, cu102, cu113 and cu115. What are the correct versions of CUDA, pytorch, torchvision and torchaudio?
I have been stuck in this problem for five days. I hope to share with anyone who has successfully established the environment. Thank you very much！
<img width="501" alt="1" src="https://user-images.githubusercontent.com/90401610/199445103-292cf5d7-970f-42c6-a130-049b4a7eecd7.png">
<img width="723" alt="2" src="https://user-images.githubusercontent.com/90401610/199445186-f7134c02-48a3-47a1-8d52-24a865019b52.png">

<img width="563" alt="3" src="https://user-images.githubusercontent.com/90401610/199445219-7260086e-4966-4731-8dc4-b8988034dd3a.png">

**Comment by raimis** [comment]
First of all, all the packages have to come from `conda-forge` channel, otherwise it guaranteed not to work.

The installation instructions are here: https://github.com/torchmd/torchmd-net#installation. It seems, you are doing something else.
