### ISSUE TITLE
No saved model

### ISSUE THREAD

**Issue by funihang** [torchmd/torchmd-net#160]
Hello, I try the command 
```
CUDA_VISIBLE_DEVICES=0 torchmd-train --conf torchmd-net/examples/ET-QM9.yaml --log-dir output/
``` 
to get the output, but there is no saved model or checkpoints under the `output` folder. So when it runs (row 158 of ./torchmdnet/scripts/train.py) `model = LNNP.load_from_checkpoint(trainer.checkpoint_callback.best_model_path)`
, it cannot find the path of the best model. I wonder what I did wrong in the training process.

**Comment by PhilippThoelke** [comment]
Did you check if there actually is no model in the output directory? I think sometimes the `best_model_path` is not working as intended.

**Comment by funihang** [comment]
yes, there are only 4 files (`hparams.yaml`, `input.yaml`, `metrics.csv`, and `splits.npz`) and one folder (`tensorboard`) under the `output` directory. 

![image](https://user-images.githubusercontent.com/55854600/211169817-397c0b79-8d9b-4bd1-8665-98dec3bcc872.png)

**Comment by PhilippThoelke** [comment]
Are you sure the model trained for at least as many epochs as the value of `save_interval` in hparams.yaml?

**Comment by funihang** [comment]
Yes, you are correct. I set the epochs less than the `save_interval`, and now I solved it. Thanks for your help.
