### ISSUE TITLE
Training for solids

### ISSUE THREAD

**Issue by JonathanSchmidt1** [torchmd/torchmd-net#163]
Hi and thank you for the great package.

We would be interested in trying to use torchmd-net to train force fields for crystal structures. As far as I can see the main changes that would have to be made, would be including periodic boundary conditions in the distance calculation (might be easy with https://github.com/felixmusil/torch_nl ) and adding the calculation of stresses. Are there any inherent issues of torchmd-net for solids that you are aware of that I missed?

best and thank you very much,
Jonathan

**Comment by guillemsimeon** [comment]
Hi Jonathan,

thanks for your interest. As far as I know, compatibility for solids would be possible with PBC and the calculation of stresses, as you mention. We are currently looking into that. Support for PBC should be immediate, and hopefully we can provide full compatibility very soon.

Guillem
