### ISSUE TITLE
What is embed_files in Custom Dataset

### ISSUE THREAD

**Issue by julien-blanchon** [torchmd/torchmd-net#178]
`torchmdnet.dataset.custom.Custom` take 3 arguments: `coordglob`, `embedglob`, `energyglob`.

For each file:
- Coord is a numpy array of lenght N with N the number of atom in the molecule
- What is embed ? My first guess was a numpy array with the Z of each atom, but this don't match the dimension
- What is energy ? Energy array seems to match the dimension of the coord array

**Comment by RaulPPelaez** [comment]
Maybe this test will help clarify:
https://github.com/torchmd/torchmd-net/blob/e20876ff79fe952db25e5fc55cc051a919ef218f/tests/test_datasets.py#L13-L45

* coord is an array of shape (n_molecules, n_atoms, 3)
* embed (could be z or whatever you want to use for the embedding) is an array of shape (n_molecules, n_atoms), note that the class refers to it as "z" anyhow.
* energy is an array of shape (n_molecules, )

**Comment by RaulPPelaez** [comment]
I am closing this, please feel free to reopen if you have further questions about it!

**Comment by julien-blanchon** [comment]
Yes this was clear thanks !
