### ISSUE TITLE
TorchMD-NET for materials

### ISSUE THREAD

**Issue by guillemsimeon** [torchmd/torchmd-net#193]
I am opening this issue to discuss the compatibility of TorchMD-NET for material sciences.
To the best of my knowledge, what it is missing in the current framework is just:
- Support for periodic boundary conditions, which would be solved by @RaulPPelaez new Distance module (support for triclinic is already possible?)
- Computation of stresses.

**Comment by RaulPPelaez** [comment]
Triclinic is possible except with the Cell list, which one can expect to be faster than the other strategies after something like 16K atoms.
