### ISSUE TITLE
How to train on extended xyz file format?

### ISSUE THREAD

**Issue by utkarshp1161** [torchmd/torchmd-net#202]

**Comment by RaulPPelaez** [comment]
You could transform your exyz into numpy files and use Custom: https://github.com/torchmd/torchmd-net/blob/62d2885823d778c6b196ca52d91cc1a7f178ec74/torchmdnet/datasets/custom.py#L7-L31
You can also transform into an already available Dataset, like Ace, and load like that:
https://github.com/torchmd/torchmd-net/blob/62d2885823d778c6b196ca52d91cc1a7f178ec74/torchmdnet/datasets/ace.py#L10-L20

Or you can write a new torch geometric Dataset for exyz.

**Comment by utkarshp1161** [comment]
Hi, can you suggest how to go about writing new torch geometric Dataset for exyz.

**Comment by RaulPPelaez** [comment]
Exyz provides utilities to read/write data from exyz files, you can take any of the available Datasets and replace.
Ase also understands exyz https://wiki.fysik.dtu.dk/ase/ase/io/formatoptions.html#xyz

You can also just write a Dataset from scratch, here are some resources:

https://pytorch-geometric.readthedocs.io/en/latest/tutorial/create_dataset.html

https://github.com/stefanch/sGDML/blob/master/scripts/sgdml_dataset_from_extxyz.py

I would start by inheriting from Custom and providing its constructor with the .npy files it requires.

**Comment by utkarshp1161** [comment]
Was able to do it, thanks.
