### ISSUE TITLE
Training equivariant transformer with OptimizedDistance

### ISSUE THREAD

**Issue by FranklinHu1** [torchmd/torchmd-net#203]
Hello,

I am currently trying to train the equivariant transformer model using the OptimizedDistance module by replacing the call to Distance() with OptimizedDistance() in torchmd-net/torchmdnet/models/torchmd_et.py. I want to train on a system with periodic boundary conditions. However, when I try running the training, I get the following traceback:
```
Traceback (most recent call last):
  File "/home/frankhu/torchmd-net/torchmdnet/scripts/train.py", line 189, in <module>
    main()
  File "/home/frankhu/torchmd-net/torchmdnet/scripts/train.py", line 137, in main
    model = LNNP(args, prior_model=prior_models, mean=data.mean, std=data.std)
  File "/home/frankhu/torchmd-net/torchmdnet/module.py", line 29, in __init__
    self.model = create_model(self.hparams, prior_model, mean, std)
  File "/home/frankhu/torchmd-net/torchmdnet/models/model.py", line 70, in create_model
    representation_model = TorchMD_ET(
  File "/home/frankhu/torchmd-net/torchmdnet/models/torchmd_et.py", line 118, in __init__
    self.distance = OptimizedDistance(
  File "/home/frankhu/torchmd-net/torchmdnet/models/utils.py", line 199, in __init__
    from torchmdnet.neighbors import get_neighbor_pairs_kernel
  File "/home/frankhu/torchmd-net/torchmdnet/neighbors/__init__.py", line 15, in <module>
    compile_extension()
  File "/home/frankhu/torchmd-net/torchmdnet/neighbors/__init__.py", line 11, in compile_extension
    cpp_extension.load(
  File "/home/frankhu/mambaforge/envs/torchmd-net/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1269, in load
    return _jit_compile(
  File "/home/frankhu/mambaforge/envs/torchmd-net/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1453, in _jit_compile
    version = JIT_EXTENSION_VERSIONER.bump_version_if_changed(
  File "/home/frankhu/mambaforge/envs/torchmd-net/lib/python3.10/site-packages/torch/utils/_cpp_extension_versioner.py", line 45, in bump_version_if_changed
    hash_value = hash_source_files(hash_value, source_files)
  File "/home/frankhu/mambaforge/envs/torchmd-net/lib/python3.10/site-packages/torch/utils/_cpp_extension_versioner.py", line 15, in hash_source_files
    with open(filename) as file:
FileNotFoundError: [Errno 2] No such file or directory: '/home/frankhu/torchmd-net/torchmdnet/neighbors/backwards.cu'
```

I saw in a previous commit that this file was removed, but it seems like the model cannot proceed with training without it. For reference, here is the change I made within torchmd_et.py:

```
self.distance = OptimizedDistance(
            cutoff_lower,
            cutoff_upper,
            max_num_pairs = -max_num_neighbors,
            return_vecs = False,
            loop = False,
            strategy = 'brute',
            include_transpose = True,
            resize_to_fit = False,
            check_errors = False,
            box = torch.diag(torch.tensor(pbc_box))
        )
```
I am running on one Nvidia H100 GPU. Any help/clarification would be greatly appreciated.

Thank you!

**Comment by RaulPPelaez** [comment]
Hi!
I accidentally mentioned this old file in the list of sources for the extension comp. The CI missed it because it is GPU only and my local tests too because the file was present in my local copy. 
Sorry for the inconvenience, I fix this in #204

**Comment by RaulPPelaez** [comment]
Also, be careful with the parameters, the current ET expects Distance to return_vecs and have self loops. You should replace the Distance line with:
```python
        self.distance = OptimizedDistance(
            cutoff_lower,
            cutoff_upper,
            max_num_pairs=-max_num_neighbors,
            return_vecs=True,
            loop=True,
        )
```

**Comment by FranklinHu1** [comment]
Perfect, thank you so much! I ultimately need this model to compile down to a torchscript module for use with OpenMM, so are there any additional changes I should make to ensure that that will work? Or is replacing Distance with Optimized distance sufficient?

**Comment by RaulPPelaez** [comment]
That should be it! But if you find any issues just let us know.

**Comment by RaulPPelaez** [comment]
Your first error is probably the one described here: https://github.com/torchmd/torchmd-net/pull/205 
We are working on it.

CUDA graphs are a separated feature and not required at all for OpenMM-Torch compatibility, your error above is telling you that some operation in ET is not CUDA graph compatible (in particular mask.all()). We have not had success thus far in training with CUDA graphs.
Setting resize_to_fit to False would require making severe modifications to ET. In that case OptimizedDistance pads the output with special values to ensure the output always has the same shape, ET does not handle this padding and thus fails when interpreting it as legal values.
check_errors set to False will silently let pairs out of the list if max_num_pairs is too low in exchange for being a bit faster. It is not really worth it if you are not using CUDA graphs, which you cant in ET currently.
The conf that will work for ET is this:
```python
        self.distance = OptimizedDistance(
            cutoff_lower,
            cutoff_upper,
            max_num_pairs=-max_num_neighbors,
            return_vecs=True,
            loop=True,
            box = torch.diag(torch.tensor(pbc_box))
        )
```

The worrying error you are getting is this:
```python
Could not find any similar ops to torchmdnet_neighbors::get_neighbor_pairs. This op may not exist or may not be currently supported in TorchScript.
```
I assumed by TorchScripting the module all operations will be placed inside the pt file. Apparently [not!](https://pytorch.org/tutorials/advanced/torch_script_custom_ops.html).
While this is not ideal, I currently do not see any workaround beyond modifying your OpenMM-Torch to load the required library:
```python
from openmmtorch import TorchForce
import torchmdnet.models.utils #This line will register the library to torch.ops
force = TorchForce("generated_mod.pt") #My generated TorchScript module
```
I am sorry for this inconvenience, I will take a look to see if something can be done.

**Comment by FranklinHu1** [comment]
Thanks for the clarifications, that was very helpful! I found that it was helpful to consolidate everything into one virtual environment because there were specific imports that were needed to make the TorchForce module to work, specifically: 
```python
from openmmtorch import TorchForce
import torchmdnet.neighbors #Addresses the missing operations error
import torch_cluster, torch_geometric #Required for some other operations within ET

force = TorchForce("generated_mod.pt") #This now works
```
With this set up, I can now run dynamics within openmm. Thanks for all your help!
