### ISSUE TITLE
Removing reference energies

### ISSUE THREAD

**Issue by RaulPPelaez** [torchmd/torchmd-net#276]
Sometimes it is useful to subtract a reference energy for each atom when training (to train on relative energies), but then have the model return total energy when doing inference. 

Note that, given that the reference energies depend on the dataset, accomplishing this requires somehow storing the reference energies as a buffer in the model.

 **We should provide first class support for this functionality**

Currently there are two independent mechanisms in place in TorchMD-Net that deal with this:

- The Atomref prior
- The remove_ref_energy option of MemmappedDataset

### The Atomref prior
This prior asks the dataset for its reference energies:
https://github.com/torchmd/torchmd-net/blob/4601b54127d6d8db1e5a1ed1314e9801b0993fac/torchmdnet/priors/atomref.py#L25
For instance, in ANI1X:
https://github.com/torchmd/torchmd-net/blob/4601b54127d6d8db1e5a1ed1314e9801b0993fac/torchmdnet/datasets/ani.py#L137-L145
This prior then creates an Embedding layer to act as a dictionary:
https://github.com/torchmd/torchmd-net/blob/4601b54127d6d8db1e5a1ed1314e9801b0993fac/torchmdnet/priors/atomref.py#L36-L37
and then adds to each atom in forward:
https://github.com/torchmd/torchmd-net/blob/4601b54127d6d8db1e5a1ed1314e9801b0993fac/torchmdnet/priors/atomref.py#L53

#### Problems
- The Embedding layer is learnable, `freeze=True` should be added for it to not be.
- There is no way to make the behavior different during training an inference.

### The remove_ref_energies dataset option

The MemmappedDataset class has a remove_ref_energy option that, if enabled makes the model see relative energies when training:
https://github.com/torchmd/torchmd-net/blob/6d8e3159cfb8bb971ecf7a2abd589735d79a7e53/torchmdnet/datasets/memdataset.py#L242-L246

#### Problems
- There is no mechanism in place to add the reference energies back during inference
- There is no reason why this only exists for MemmappedDataset and not the rest.
- This behavior is undocumented

Both of this depend on the Dataset defining the function "get_atomref". Moreover, MemmappedDataset requires an additional "compute_ref_energies" method that AFAICT simply sums up the results of get_atomref. The former req should go IMO.

#### The current dataset option "remove_ref_energy" can be used in create_model to signal "store ref energies as a buffer in the model". Another flag can then be turned on during inference ("add_ref_energy"?) 

To accomplish this I can think of two ways:
- The Atomref prior could have a couple of flags, one to freeze the references (should default to True) and another to turn it on/off. "remove_ref_energy" would then add Atomref as a prior turned off and with frozen weights. During inference the add_ref_energy would turn the already present Atomref prior on.

- It makes more sense to me that this goes to the dataset/dataloader than a prior. I would deprecate the Atomref prior and instead deal with ref energies in the model itself, for instance adding to TorchMD_Net:

```python
if self.add_back_ref_energies:
   y += self.stored_ref_energies
```

cc @PhilippThoelke @stefdoerr, I would like to hear your thoughts on this.

**Comment by PhilippThoelke** [comment]
I would argue that if the save atomref flag is set in create_model we should probably turn the atomref prior into just a part of the model. Otherwise one has to remember to also define the prior model when setting the flag. The other option would be to add a "training" flag to the pre- and post-reduce functions in the prior class and change only the atomref prior. I would actually argue for the second option as it keeps the main model agnostic about what it is predicting (doesn't always have to be energies).
