### ISSUE TITLE
NNPOps tests broken

### ISSUE THREAD

**Issue by PhilippThoelke** [torchmd/torchmd-net#85]
@raimis the NNPOps tests seem to be broken, could you look into it?
E.g. in PR #84: https://github.com/torchmd/torchmd-net/pull/84/checks

**Comment by raimis** [comment]
@PhilippThoelke I have already seen this with the other PR. I'll try to fix today.

**Comment by raimis** [comment]
`conda-forge` has rebuilt TorchANI (https://github.com/conda-forge/torchani-feedstock/pull/10) for PyTorch 1.11, but not yet NNPOps (https://github.com/conda-forge/nnpops-feedstock/pull/3).

**Comment by mikemhenry** [comment]
I'm working on the NNPOps rebuild right now!

**Comment by mikemhenry** [comment]
Rebuilt! https://github.com/conda-forge/nnpops-feedstock/pull/3

**Comment by raimis** [comment]
Thanks @mikemhenry. Meanwhile I found a quick fix (https://github.com/torchmd/torchmd-net/pull/87). Later update the dependencies to use PyTorch 1.11.
