### ISSUE TITLE
Question about adding missing atoms in protein

### ISSUE THREAD

**Issue by psp3dcg** [torchmd/torchmd-net#95]
Hi, awesome work! I meet some partly broken protein (with some missing side chain atoms) when dealing with pdb file and I usually use pdbfixer(https://github.com/openmm/pdbfixer) or pdb2pqr(https://www.cgl.ucsf.edu/chimera/docs/UsersGuide/midas/pdb2pqr.html) to repair them. After reading your paper. I just wonder it is possible to train a pdb-fix-net based on torchmd-net. Could you please give me some tips? Thanks~:)

**Comment by psp3dcg** [comment]
> 

OK，thank you for your quick reply~ But how can I get side-chain atoms' protonation states?(I just search information about it, is propka able to get protonation?). Moreover, how to compute accurate atoms' 3D coordinate from their protonation states?(Sorry, I am a new beginner about computational chemistry,,,)

**Comment by psp3dcg** [comment]
Actually, I am studying predicting protein 3d structure based on neural networks. If the backbone atoms' coordinates have been calculated, is it possible to use torchmd-net to add missing side-chain atom like pdbfixer? Thanks~ :)

**Comment by stefdoerr** [comment]
Moleculekit systemPrepare function uses propka and pdb2pqr to add missing atoms to side-chains. It all depends on how much you are missing. If you are missing big chunks of the protein neural networks could make sense. There are already some implementations published IIRC.
I don't believe torchmd-net is ideal for this as it's meant for calculating atomic properties with known coordinates. Look at in-painting networks

**Comment by peastman** [comment]
> But how can I get side-chain atoms' protonation states?

To a first approximation it just depends on pH.  Most sites will have only one protonation state that is significantly populated.  Which state that is depends on pH.  There are exceptions though.  If the pH is close to the crossover point, there can be multiple states that are significantly populated.  In that case, you really want to use a simulation protocol that allows the state to switch back and forth during the simulation.  That isn't done very often, though, at least in molecular dynamics.  The most important case is HIS, which has multiple populated states at pH 7.  The other important correction is that you really should pick it based on local pH.  If there's a nearby charge that attracts or repels hydrogens, the local pH can be significantly different from the global one.  But again this is rarely taken into account in simulations.

**Comment by psp3dcg** [comment]
> Moleculekit systemPrepare function uses propka and pdb2pqr to add missing atoms to side-chains. It all depends on how much you are missing. If you are missing big chunks of the protein neural networks could make sense. There are already some implementations published IIRC. I don't believe torchmd-net is ideal for this as it's meant for calculating atomic properties with known coordinates. Look at in-painting networks maybe or generally at other protein structure prediction networks.

OK, thanks for your help~ :)

**Comment by psp3dcg** [comment]
> > But how can I get side-chain atoms' protonation states?
> 
> To a first approximation it just depends on pH. Most sites will have only one protonation state that is significantly populated. Which state that is depends on pH. There are exceptions though. If the pH is close to the crossover point, there can be multiple states that are significantly populated. In that case, you really want to use a simulation protocol that allows the state to switch back and forth during the simulation. That isn't done very often, though, at least in molecular dynamics. The most important case is HIS, which has multiple populated states at pH 7. The other important correction is that you really should pick it based on local pH. If there's a nearby charge that attracts or repels hydrogens, the local pH can be significantly different from the global one. But again this is rarely taken into account in simulations.

OK, thanks for the reply I will try it~ :)

**Comment by psp3dcg** [comment]
> 

Sorry to bother you, could you please tell me the full name of 'IIRC'? I searched it but did not get the right result...

**Comment by psp3dcg** [comment]
> Moleculekit systemPrepare function uses propka and pdb2pqr to add missing atoms to side-chains. It all depends on how much you are missing. If you are missing big chunks of the protein neural networks could make sense. There are already some implementations published IIRC. I don't believe torchmd-net is ideal for this as it's meant for calculating atomic properties with known coordinates. Look at in-painting networks maybe or generally at other protein structure prediction networks.

Sorry to bother you, could you please tell me the full name of 'IIRC'? I searched it but did not get the right result...

**Comment by stefdoerr** [comment]
If I remember correctly

**Comment by psp3dcg** [comment]
> If I remember correctly

OK, thank U~
